package io.adev.test_task.data.cloud.exception;

public class ParseException extends Exception {
}
